### ISSUE TITLE
Implement Quiz Management

### ISSUE THREAD

**Issue by lyubaintech** [TEAM-1-FIRST-PROJECT/Quizzle#18]
- [x] Admins can edit or delete any quiz.
- [x] Scoreboard Moderation: Admins could be able to oversee scoreboards for tests and address any discrepancies.
- [x] Educator Groups: Educators should be separated into groups. Educators in the same group can edit or delete any quiz, that is created by someone on their team.

**Comment by TodorT0420** [comment]
Educator Groups: Educators should be separated into groups. Educators in the same group can edit or delete any quiz, that is created by someone on their team. 
 
- Мust implement when the educator click view group quizzes button to see the quizzes which created only from members in that group
